### ISSUE TITLE
Nicola, check this out!!

### ISSUE THREAD

**Issue by daviddias** [wanderer/merkle-trie#17]
@nicola, @wanderer just updated the whole module to incorporate some of the things that we discussed in Seattle, that are related with this me and you talked about too, namely: Being able to manipulate JSON objects at will and then let the 'thing' build and shard the graph as we intended to.

Check the USAGE https://github.com/ipld/js-ipld-graph-builder#usage the example is pretty good.

**Comment by daviddias** [comment]
//cc @mikolalysenko @substack @jbenet

**Comment by nicola** [comment]
@wanderer this is awesome work!

This is much simpler than my attempt at this (https://github.com/nicola/js-simple-ipld/blob/master/test/basic-usage.js), look forward to try this out soon!

**Comment by wanderer** [comment]
thanks guys! please let me know if there is anything to do to improve this. Thanks
