### ISSUE TITLE
Greenkeeper

### ISSUE THREAD

**Issue by wanderer** [wanderer/merkle-trie#18]
hey @diasdavid greenkeeper is still not running on here and I don't have the permissions to enable it

**Comment by daviddias** [comment]
Hey @wanderer , it was, then we [disabled Greenkeeper for all the repos](https://github.com/ipfs/community/issues/197), but I just enabled it again for this repo :) you should be getting a issue and PR from it in some minutes :) 

```
» greenkeeper enable
🌴  info enable The GitHub slug is: ipld/js-ipld-graph-builder
ipld/js-ipld-graph-builder enabled
```
