### ISSUE TITLE
Error on boot

### ISSUE THREAD

**Issue by vmatekole** [wanderer/merkle-trie#24]
I get the following error on startup in my Meteor 1.5 installation. Let me know if you need further info. 
``` js
W20170627-23:07:35.849(2)? (STDERR) packages/modules.js:541
W20170627-23:07:35.851(2)? (STDERR) module.exports = class Graph {
W20170627-23:07:35.852(2)? (STDERR)                  ^^^^^
W20170627-23:07:35.852(2)? (STDERR) 
W20170627-23:07:35.853(2)? (STDERR) SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
W20170627-23:07:35.853(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170627-23:07:35.854(2)? (STDERR)     at /Users/Shared/code/ethereum-reactjs/app/.meteor/local/build/programs/server/boot.js:331:30
W20170627-23:07:35.855(2)? (STDERR)     at Array.forEach (native)
W20170627-23:07:35.855(2)? (STDERR)     at Function._.each._.forEach (/Users/PI/.meteor/packages/meteor-tool/.1.5.0.4u33bv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170627-23:07:35.855(2)? (STDERR)     at /Users/Shared/code/ethereum-reactjs/app/.meteor/local/build/programs/server/boot.js:158:5
W20170627-23:07:35.856(2)? (STDERR)     at /Users/Shared/code/ethereum-reactjs/app/.meteor/local/build/programs/server/boot.js:387:5
W20170627-23:07:35.857(2)? (STDERR)     at Function.run (/Users/Shared/code/ethereum-reactjs/app/.meteor/local/build/programs/server/profile.js:510:12)
W20170627-23:07:35.858(2)? (STDERR)     at /Users/Shared/code/ethereum-reactjs/app/.meteor/local/build/programs/server/boot.js:386:11
```

**Comment by victorb** [comment]
What node version are you using? If using < 7, could you try updating to latest node stable and report if things are working? Latest stable is `8.1.2` currently

**Comment by vmatekole** [comment]
@VictorBjelkholm Meteor 1.5 runs 4.8.3 ... Is that a problem?

**Comment by wanderer** [comment]
@VictorBjelkholm graph-builder is using es6 `class`. But you should be able to use it with the `--harmony` flag on 4. A newer version (7 or 8)  of nodejs is best though.

**Comment by vmatekole** [comment]
@VictorBjelkholm and @wanderer  — I found the root cause of the  issue. It appears, there is a deployment pattern for NPM packages that I've only become aware of.... ES6 code should be transpiled with Babel before being published, so the package can be compatible in multiple environments — in my case Meteor 1.5. Please note, ES6 is being used in my stack but appears Meteor isn't transpiling NPM packages loaded.

I can provide a pull request — if the author would like to have the package compatible with a broader set of environments. Let me know.

**Comment by wanderer** [comment]
@vmatekole i would rather leave it up to the user to trancompile stuff. But I also have no knowledge of babel or meteor

**Comment by vmatekole** [comment]
hi @wanderer — I think it is correct call, especially as Meteor 1.6 aims to solve ability to run native ES6 modules as NPM packages as part of upgrade to Node v6 —https://github.com/meteor/meteor/pull/8728. Just discovered, and am running pre-release 1.6 on my ongoing project now — this appears to have solved the problem. Closing issue...
