### ISSUE TITLE
Watching graph updates

### ISSUE THREAD

**Issue by vmatekole** [wanderer/merkle-trie#25]
I'm working on an IPFS based reactive solution in Apollo/GraphQL. Rather than poll for updates on the Graph — the desire is to have updates event-based. 
E.g. 
``` js
graph.watch(node, path, result => {
  // Push updates to client
})
```
Updates to the Graph can then be pushed to client automatically. Has there been any thoughts around this?

**Comment by daviddias** [comment]
Hi @vmatekole, sounds exciting, is there something we can check out (code, demo)? It helps us to help :)

I believe what you are looking for is a 'feed of changes', in IPFS these can be achieved through many ways:

- Using IPNS - IPNS is a name system that lets you distribute updates over the network that are signed (so you know you can trust the latest update)
- PubSub - Broadcast changes as they happen

On top of this, people have been append-only logs and [CRDTs](https://github.com/ipfs/research-CRDT). See the IIIFDB demo:
- https://www.youtube.com/watch?v=8xE1MEyZsbo
- https://www.youtube.com/watch?v=hscU-Mg242M

@pgte will have more pointers for these :)

**Comment by pgte** [comment]
@vmatekole there are a bunch of projects inside [the ipfs-labs org](https://github.com/ipfs-labs) that have experimented with using pub-sub to communicate updates.

They all rely on [ipfs-pubsub-room](https://github.com/ipfs-labs/ipfs-pubsub-room) to track membership, as well as exchange p2p and broadcast messages.

There are two approaches here already implemented for your reference:

* the kv-store with sync in [tevere](https://github.com/ipfs-labs/tevere), which is based on a log and propagating log heads, or
* the CRDT approach using [Yjs](http://y-js.org) and the [y-ipfs-connector](https://github.com/ipfs-labs/y-ipfs-connector), which uses IPFS pubsub as a transport.

Ping me if you would like to discuss or some more pointers! :)

**Comment by vmatekole** [comment]
Thanks @pgte and @diasdavid for the info. I'll take a deep dive. I just discovered — https://github.com/ipfs/interface-ipfs-core/tree/master/API/pubsub and am experimenting now. This could be a good first step for us. 

I'll update this issue with repo details once we're up and running and will undoubtedly have more questions.

**Comment by daviddias** [comment]
Closing this issue for now. @vmatekole let us know if anything else comes up :)
