### ISSUE TITLE
How to create a graph based on existing DAG nodes

### ISSUE THREAD

**Issue by vmatekole** [wanderer/merkle-trie#27]
I have added an object using 
``` ipfs.dag.put(obj) ```
``` // Result multihash — zdpuAypJXbmGCLweJBL6R1iBpDGJyP8LU1BwZjzRjwNxohzvE```

```js
graph.tree(
      {"/": "zdpuAypJXbmGCLweJBL6R1iBpDGJyP8LU1BwZjzRjwNxohzvE"},
      Infinity
    ).done((res)=> {
      console.log(res);
    });
// Result undefined
```

Essentially, I want to determine how graphs can interoperate with IPFS node DAG's that are created independently of the Graph API. Finally, how does one get hold of a DAG's multihash?

**Comment by wanderer** [comment]
@vmatekole do you mean like this?
```javascript
const IPFS = require('ipfs')
const Graph = require('ipld-graph-builder')
const ipfs = new IPFS()

ipfs.on('start', async () => {

  const obj = { simple: 'object' }

  const cid = await ipfs.dag.put(obj, { format: 'dag-cbor', hashAlg: 'sha3-512' })
  const graph = new Graph(ipfs.dag)
  const a = {
    '/': cid.toBaseEncodedString()
  }
  await graph.tree(a, Infinity)
  console.log(JSON.stringify(a, null, 2))
})
```

**Comment by wanderer** [comment]
> Finally, how does one get hold of a DAG's multihash?

`graph.flush` returns the CID, [encoded as a string](https://github.com/ipld/js-ipld-graph-builder/blob/master/index.js#L176) which contains a MH

**Comment by vmatekole** [comment]
@wanderer  strange, similar to what I already had but my implementation doesn't work:
``` js
  ipfs.dag.put(
    obj,
    dagOpts
  ).done((res)=> {
    console.log('Added org');
    console.log(res.toBaseEncodedString());
    a = {'/': res.toBaseEncodedString()};
    graph.tree(
      a,
      Infinity
    ).done((res)=> {
      console.log(res);
    });
  });
```

**Comment by vmatekole** [comment]
@wanderer Ahhh, I see what the issue is... The result from ```graph.tree``` is not returned via a promise. The object, in this case ```a``` is mutated with result. Is that intended?

**Comment by wanderer** [comment]
> in this case a is mutated with result. Is that intended?

yep, i guess i could return it also

**Comment by wanderer** [comment]
@vmatekole ok fixed tree so it now also returns the correct value
