### ISSUE TITLE
Use Graph Builder for Unixfs

### ISSUE THREAD

**Issue by daviddias** [wanderer/merkle-trie#32]
@pgte It would be interesting try to reimplement the sharding and graph building logic in unixfs-engine with this module and see if its API fits our needs. It would be a first step to converge on an API that we will eventually expose through js-ipfs (e.g `ipfs.dag.builder`)

@vmx it would be good for you to check this too :)

**Comment by pgte** [comment]
Sounds good, added this to my to-do list :)

**Comment by rvagg** [comment]
closing for archival
